first version
grafyu/go-first-floor-sprint-five pull request #1
Opened 2024-02-17 21:33 UTC by grafyu

Первый вариант решения

2024-02-18 23:01 UTC, dirtymew requested changes
Юрий

дал комментарии - нужно немного переделать

2024-02-18 23:01 UTC, dirtymew commented on main.go
> +	return t.distance() / float64(t.Duration.Hours())
тут 3 момента:
- комментарии из задания лучше убрать
- тут деление на 0 - нужно избежить и в других формулах тоже
- дополнительно приводить к float64 нетребуется - t.distance уже float64

2024-02-18 23:01 UTC, dirtymew commented on main.go
> +	return 0.00
можно просто 0 - go сам все сделает

2024-02-18 23:01 UTC, dirtymew commented on main.go
> +		i.Duration.Minutes(),		// minutes
комментарии принято оставлять на одном языке - если английском то все на нем, если на русском то все на русском

2024-02-18 23:01 UTC, dirtymew commented on main.go
> +	Calories() float64
верно обьявил интерфейс

2024-02-18 23:01 UTC, dirtymew commented on main.go
> +			r.Weight / float64(MInKm) * r.Duration.Hours() * float64(MinInHours))
константы не нужно приводить к другому типу) 

очень много лишних приведений - попробуй без них

2024-02-18 23:01 UTC, dirtymew commented on main.go
> +	return r.Training.TrainingInfo()
верно переопределил метод - воспользовался методом встроенной структуры

2024-02-18 23:01 UTC, dirtymew commented on main.go
> +	return ((CaloriesWeightMultiplier * w.Weight + (math.Pow(w.meanSpeed() * KmHInMsec, 2) / w.Height) *
тут тоже деление на 0 возможно - нужно избежать

и не использована константа CmInM - те формула неверная

2024-02-18 23:01 UTC, dirtymew commented on main.go
> +	return s.Training.TrainingInfo()
раз уж будем исправлять то давай и это поправим

тут все ты верно сделал по заданию
но в этом случае для Плаванья неверно посчитается скорость - попробуй понять почему...

исправить это легко - можно полностью переопределить метод TrainingInfo()

2024-02-18 23:01 UTC, dirtymew commented on main.go
> +	return 0.00
@grafyu  тут не исправил

2024-02-18 23:01 UTC, dirtymew commented on main.go
> +	var iMsg InfoMessage
тут можно лучше 

```
return InfoMessage{
    TrainingType: t.TrainingType
    ....
}
```

2024-02-18 23:01 UTC, dirtymew commented on main.go
> +		i.Duration.Minutes(), // minutes
все комментарии кроме терминов пишут обычно на одном языке

2024-02-18 23:01 UTC, dirtymew commented on main.go
>  	// вставьте ваш код ниже
тут избавиться от деления на 0 можно так
```
if w.Height == 0 {
    return 0
}
```

2024-02-18 23:01 UTC, dirtymew commented on main.go
> +	if walking.Duration <= 0 {
не верно меня понял

это стоит сделать на уровне функций  - не тут.

еще один момент - старайся избегать else и особенно else if
лучше обойтись просто if  или если  много условий то switch.

Такой код(if else if else) сложно читать очень тяжело поддерживать - соответственно это путь к багам. по возможности избегай этого

2024-02-20 07:36 UTC, grafyu commented on main.go
> +	return s.Training.TrainingInfo()
"исправить это легко - можно полностью переопределить метод TrainingInfo()"

Можно ли при этом переопределять сигнатуру метода TrainingInfo() ?

2024-02-20 08:11 UTC, dirtymew commented on main.go
> +	return s.Training.TrainingInfo()
можно все - но не стоит, это уже будет сильно отличаться от задания.

Как ты хотел бы ее поменять?

2024-02-20 08:57 UTC, grafyu commented on main.go
> +	return s.Training.TrainingInfo()
переопределил только поле Speed через метод верхней структуры
'func (s Swimming) TrainingInfo() InfoMessage { ...'

2024-02-20 12:29 UTC, dirtymew approved these changes
Юрий задание выполнено, вопросов нет - зачет

2024-02-20 12:29 UTC, dirtymew commented on main.go
> +	return t.distance() / float64(t.Duration.Hours())
ну возвращать не буду - лишнее приведение типа float64

2024-02-20 12:49 UTC, merged